#!/usr/bin/env bash

if [[ -z "$DOTFILES_DIR" ]]; then
    echo "[!] Fatal: DOTFILES_DIR is not set" >&2
    echo "    this usually happens when someone tries to execute 'dotfiles_apply' directly" >&2
    echo "    which is not recommended. Instead use 'dotfiles apply' which is a wrapper that" >&2
    echo "    sets all required environment variables." >&2
    exit 2
fi

source "$DOTFILES_DIR/dotfiles_lib"

if [[ $# -lt 1 ]]; then
    msg ! "Wrong argument count"
    exit 1
fi

# Check if this module is a dependency
IS_DEP=0;
if [[ "$1" == "-d" || "$1" == "--dependency" ]];then
    shift
    IS_DEP=1;
fi

MODULE="$DOTFILES_DIR/$1"

if [[ -d "$MODULE" ]];then
    msg + "Applying module '$1'."
else
    msg ! "Module '$1' doesn't exist"
    exit 2
fi

# Check if module has all the necesary files
check_integrity "$MODULE"
if (( $? != 0 ));then
    exit $?
fi


# Get all dependencies 
mapfile -t DEPENDENCIES < <(process "$MODULE/.dependencies") 
if (( ${#DEPENDENCIES[@]} > 0 )); then
    msg H "Module '$1' has the following dependencies:"
    FLAGGED=()
    for dep in "${DEPENDENCIES[@]}"; do
            FLAGGED+=("-d" "$dep")
            msg . "- $dep"
    done
    msg H "Applying dependencies first"
    "$0" "${FLAGGED[@]}"
    if (($? != 0 ));then
        msg ! "Applying dependencies for module '$1' failed"
        exit $?
    fi
    msg + "Module '$1' dependencies successfully applied"
fi


TARGET="$(process "$MODULE/.target")"
TARGET="${TARGET/#\~/$HOME}" 
    
if [[ ! -d "$TARGET" ]]; then
        msg ! "The target directory '$TARGET' for module '$1' does not exist or is not a directory"
        exit 3
fi

msg H "Applying stow $1 to target '$TARGET'"
stow --target "$TARGET"                 \
     --dir "$DOTFILES_DIR"              \
     --ignore="^\.target$"              \
     --ignore="^\.stow-local-ignore$"   \
     --ignore="^\.dependencies$"        \
     --ignore="^\.is_not_dep$"          \
     --ignore="^\.dep_count$"           \
     --ignore="^\.gitignore$"           \
     --verbose                          \
     $1 2>&1
if (( $? != 0 ));then
    msg ! "Stow returned error code $?"
    exit $(?+1)
fi
msg = "stow $1 has been applied" 
   
# Increment dependency count
read -r dep_count <  "$MODULE/.dep_count"
((dep_count++))

if (( $IS_DEP == 0 ));then
    if [[ -e "$MODULE/.is_not_dep" ]];then
        msg H "The module was already manually applied:"
        msg . "keeping dependency count intact"
    else
        msg H "Marking module as manually applied"
        touch "$MODULE/.is_not_dep"
        echo "$dep_count" > "$MODULE/.dep_count"
    fi
else
    echo "$dep_count" > "$MODULE/.dep_count"
fi

shift 
if (( $# > 0 ));then
    msg H "Proceeding with next item (module '$1')"
    exec "$0" "$@"
fi
