#!/usr/bin/env bash


if [[ -z "$DOTFILES_DIR" ]]; then
    echo "[!] Fatal: DOTFILES_DIR is not set" >&2
    echo "    this usually happens when someone tries to execute 'dotfiles_list' directly" >&2
    echo "    which is not recommended. Instead use 'dotfiles list' which is a wrapper that" >&2
    echo "    sets all required environment variables." >&2
    exit 2
fi
source "$DOTFILES_DIR/dotfiles_lib"

msg + "List of modules:"
for module in "$DOTFILES_DIR"/*;do
    if [ -d "$module" ];then
        check_integrity "$module"
        if (( $? != 0 ));then
            msg ! "Integrity check failed with error code $1"
        fi
        dep_count=$(<"$module/.dep_count")
        if [[ -e "$module/.is_not_dep" ]];then
            msg . "- ${module##*/}: [ACTIVATED] dependency to $((dep_count - 1)) modules"
        else 
            msg . "- ${module##*/}: dependency to $dep_count modules"
        fi
    fi
done
