#!/usr/bin/env bash

# Args: <module> 

IS_DEP=0;
if [[ "$1" == "-d" || "$1" == "--dependency" ]];then
    shift
    echo "[+] Dependency flag activated"
    IS_DEP=1;
fi

if [[ $# -lt 1 ]]; then
    echo "[!] Fatal: Wrong argument count" >&2
    exit 1
fi


if [[ -z "$DOTFILES_DIR" ]]; then
    echo "[!] Fatal: DOTFILES_DIR is not set" >&2
    echo "    this usually happens when someone tries to execute 'dotfiles_apply' directly" >&2
    echo "    which is not recommended. Instead use 'dotfiles apply' which is a wrapper that" >&2
    echo "    sets all required environment variables." >&2
    exit 2
fi
MODULE="$DOTFILES_DIR/$1"

if [[ -d "$MODULE" ]];then
    echo "[+] Applying module '$1'"
else
    echo "[!] Fatal: Module '$1' doesn't exist" >&2
    exit 3
fi


"$DOTFILES_DIR/validity_check" "$MODULE"
if (( $? != 0 ));then
    exit $?
fi

TARGET="$("$DOTFILES_DIR/process" "$MODULE/.target")"
TARGET="${TARGET/#\~/$HOME}" 
echo "[+] Targeting '$TARGET'"

if [[ ! -d "$TARGET" ]]; then
    echo "[!] Fatal: The target directory '$TARGET' does not exist or is not a directory"
    exit 6
fi

stow --target "$TARGET"    \
     --dir "$DOTFILES_DIR" \
     --ignore="$MODULE/.target"    \
     --ignore="$MODULE/.stow-local-ignore" \
     --ignore="$MODULE/.dependencies" \
     --ignore="$MODULE/.is_not_dep" \
     --ignore="$MODULE/.dep_count" \
     --ignore="$MODULE/.gitignore" \
     --verbose             \
     $1 2>&1

if (( $? != 0 ));then
    echo "[!] Fatal: An error happened with stow"
    exit 7
fi


if [[ $IS_DEP -eq 1 ]];then
    read -r dep_count <  "$MODULE/.dep_count"
    ((dep_count++))
    echo "$dep_count" > "$MODULE/.dep_count"
else 
    echo "1" > "$MODULE/.dep_count"
    touch "$MODULE/.is_not_dep"
fi

echo "[=] All '$1' symlinks successfully created"

mapfile -t DEPENDENCIES < <("$DOTFILES_DIR/process" "$MODULE/.dependencies")
if (( ${#DEPENDENCIES[@]} > 0 ));then 
    echo "[+] Adding dependencies to list"
    printf '  - %s\n' "${DEPENDENCIES[@]}"
fi

shift 
if (( $# > 0 || ${#DEPENDENCIES[@]} > 0 ));then
    FLAGGED=()
    for dep in "${DEPENDENCIES[@]}"; do
        FLAGGED+=("-d" "$dep")
    done
    echo "[#] Proceeding with next item"
    exec "$0" $@ "${FLAGGED[@]}"
fi
