#!/usr/bin/env bash
# Args: <module> 

if [[ -z "$DOTFILES_DIR" ]]; then
    echo "[!] Fatal: DOTFILES_DIR is not set" >&2
    echo "    this usually happens when someone tries to execute 'dotfiles_apply' directly" >&2
    echo "    which is not recommended. Instead use 'dotfiles apply' which is a wrapper that" >&2
    echo "    sets all required environment variables." >&2
    exit 2
fi
source "$DOTFILES_DIR/dotfiles_lib"

if [[ $# -lt 1 ]]; then
    msg ! "Wrong argument count"
    exit 1
fi

# Check if this module is a dependency
IS_DEP=0;
if [[ "$1" == "-d" || "$1" == "--dependency" ]];then
    shift
    IS_DEP=1;
fi

MODULE="$DOTFILES_DIR/$1"

if [[ -d "$MODULE" ]];then
    msg + "Removing module '$1'."
else
    msg ! "Module '$1' doesn't exist"
    exit 2
fi

# Check if module has all the necesary files
check_integrity "$MODULE"
if (( $? != 0 ));then
    exit $?
fi

# Get dependency count
dep_count=0
read -r dep_count <  "$MODULE/.dep_count"
((dep_count--))

TARGET="$(process "$MODULE/.target")"
TARGET="${TARGET/#\~/$HOME}" 
if [[ ! -d "$TARGET" ]]; then
        msg ! "The target directory '$TARGET' for module '$1' does not exist or is not a directory"
        exit 3
fi

if (( $dep_count <= 0 ));then
    msg H "Applying stow -D $1 to target '$TARGET'" 
    stow --target "$TARGET"    \
         --dir "$DOTFILES_DIR" \
         --verbose             \
         --delete              \
          $1 2>&1
    if (( $? != 0 ));then
        msg !!! "Stow returned error code $?"
        exit $?
    fi

    if [[ -e "$MODULE/.is_not_dep" ]];then
        rm "$MODULE/.is_not_dep"
    fi

    echo "0" > "$MODULE/.dep_count"
    
    if (( $dep_count < 0 ));then
        msg - "module '$1' was already removed"
    else
        msg = "module '$1' has been removed" 
    
        # Get all dependencies 
        mapfile -t DEPENDENCIES < <(process "$MODULE/.dependencies") 
        if (( ${#DEPENDENCIES[@]} > 0 )); then
            msg H "Module '$1' has the following dependencies:"
            FLAGGED=()
            for dep in "${DEPENDENCIES[@]}"; do
                    FLAGGED+=("-d" "$dep")
                    msg . "- $dep"
            done
            msg H "Removing dependencies next"
            "$0" "${FLAGGED[@]}"
            if (($? != 0 ));then
                msg ! "Removing dependencies for module '$1' failed"
                exit $?
            fi
            msg + "Module '$1' dependencies successfully removed"
        fi
    fi
else 
    if (( $IS_DEP == 0 ));then
        msg + "Removing manually installed flag"
        rm "$MODULE/.is_not_dep"
    fi
    echo $dep_count > "$MODULE/.dep_count"
    msg + "Skipping module '$1' because it's still a dependency"
fi

shift 
if (( $# > 0 ));then
    msg H "Proceeding with next item"
    exec "$0" "$@"
fi




