#!/usr/bin/env bash
# Args: <module> 

if [[ $# -lt 1 ]]; then
    echo "[!] Fatal: Wrong argument count" >&2
    exit 1
fi

if [[ -z "$DOTFILES_DIR" ]]; then
    echo "[!] Fatal: DOTFILES_DIR is not set" >&2
    echo "    this usually happens when someone tries to execute 'dotfiles_remove' directly" >&2
    echo "    which is not recommended. Instead use 'dotfiles remove' which is a wrapper that" >&2
    echo "    sets all required environment variables." >&2
    exit 2
fi
MODULE="$DOTFILES_DIR/$1"

if [[ -d "$MODULE" ]];then
    echo "[+] Removing module '$1'"
else
    echo "[!] Fatal: Module '$1' doesn't exist" >&2
    exit 3
fi

"$DOTFILES_DIR/validity_check" "$MODULE"
if (( $? != 0 ));then
    exit $?
fi

DEPENDENCIES=()

dep_count=0
read -r dep_count <  "$MODULE/.dep_count"
((dep_count--))
if (( $dep_count >= 0 ));then 
    TARGET="$("$DOTFILES_DIR/process" "$MODULE/.target")"
    TARGET="${TARGET/#\~/$HOME}" 
    echo "[+] Targeting '$TARGET'"
    
    if [[ ! -d "$TARGET" ]]; then
        echo "[!] Fatal: The target directory '$TARGET' does not exist"
        exit 6
    fi
    
    
    echo "$dep_count" > "$MODULE/.dep_count"
    
    if (( $dep_count == 0 ));then
        stow --target "$TARGET"    \
             --dir "$DOTFILES_DIR" \
             --verbose             \
             --delete              \
             $1 2>&1
    
        if [[ $? != 0 ]];then
            echo "[!] Fatal: An error happened with stow"
            exit 7
        fi
        
        echo "[=] All '$1' symlinks successfully removed"
        
        if [[ -e "$MODULE/.is_not_dep" ]];then
            rm "$MODULE/.is_not_dep"
        fi
        
        mapfile -t DEPENDENCIES < <("$DOTFILES_DIR/process" "$MODULE/.dependencies")
    else
        echo "[+] Skipped because it's still a dependency"
    fi
else 
    echo "[=] Skipped because it has already been completely removed"
fi

shift 
if (( $# > 0 || ${#DEPENDENCIES[@]} > 0 ));then
    echo "[#] Proceeding with next item"
    exec "$0" $@ "${DEPENDENCIES[@]}"
fi




