#!/usr/bin/env bash

SCRIPT_PATH=$(which $0) # This gives us the folder where this script is located
DOTFILES_DIR="${SCRIPT_PATH%/*}"
export DOTFILES_DIR

usage() {
    cat $DOTFILES_DIR/dotfiles_help.txt >&2
}

call(){
    script=$1
    shift
    "$DOTFILES_DIR/$script" $@
    if [[ $? != 0 ]];then
        exit $?
    fi
}


SUBCOMMAND=$1
shift
case "$SUBCOMMAND" in 
    apply|a|add)
        call dotfiles_apply $@
        echo "[=] All module sucessfully applied!"
        ;;
    remove|revert|r|delete|deactivate)
        call dotfiles_remove $@
        echo "[=] All module successfully deactivated!"
        ;;
    help|h|man|--help|-h)
        exec 2>&1
        usage
        ;;
    list|l)
        call dotfiles_list $@
        ;;
    *)
        echo "[!] Fatal: Unknown command '$SUBCOMMAND'" >&2
        usage
        exit 255;
        ;;
esac


