#!/usr/bin/env bash

SOURCE_DIR="$0"
DOTFILES_DIR="${SOURCE_DIR%/*}/"
export DOTFILES_DIR

source "$DOTFILES_DIR/dotfiles_lib"

usage() {
    msg ? "Usage: dotfiles <subcommand>"
    cat $DOTFILES_DIR/dotfiles_help.txt >&2
}

call(){
    script=$1
    shift
    "$DOTFILES_DIR/$script" $@
    if [[ $? != 0 ]];then
        exit $?
    fi
}


SUBCOMMAND=$1
shift
case "$SUBCOMMAND" in 
    apply|a|add)
        call dotfiles_apply $@
        msg = All modules applied
        ;;
    remove|revert|r|delete|deactivate)
        call dotfiles_remove $@
        msg = All modules removed
        ;;
    help|h|man|--help|-h)
        exec 2>&1
        usage
        ;;
    list|l)
        call dotfiles_list $@
        ;;
    clear|c)
        call dotfiles_clear $@
        ;;
    *)
        msg ! "Unknown command '$SUBCOMMAND'"
        usage
        exit 255;
        ;;
esac


