#!/usr/bin/env bash

# Args: <module> 

IS_DEP=0;
if [[ "$1" == "-d" || "$1" == "--dependency" ]];then
    shift
    echo "[+] Dependency flag activated"
    IS_DEP=1;
fi

if [[ $# -lt 1 ]]; then
    echo "[!] Fatal: Wrong argument count" >&2
    exit 1
fi


if [[ -z "$DOTFILES_DIR" ]]; then
    echo "[!] Fatal: DOTFILES_DIR is not set" >&2
    echo "    this usually happens when someone tries to execute 'dotfiles_apply' directly" >&2
    echo "    which is not recommended. Instead use 'dotfiles apply' which is a wrapper that" >&2
    echo "    sets all required environment variables." >&2
    exit 2
fi
MODULE="$DOTFILES_DIR/$1"

if [[ -d "$MODULE" ]];then
    echo "[+] Applying module '$1'"
else
    echo "[!] Fatal: Module '$1' doesn't exist" >&2
    exit 3
fi


"$DOTFILES_DIR/validity_check" "$MODULE"
if (( $? != 0 ));then
    exit $?
fi

read -r dep_count <  "$MODULE/.dep_count"
((dep_count++))
if [[ ! -e "$MODULE/.is_not_dep" ]];then

    mapfile -t DEPENDENCIES < <("$DOTFILES_DIR/process" "$MODULE/.dependencies")
    if (( ${#DEPENDENCIES[@]} > 0 ));then 
        echo "[+] Adding dependencies to list"
        printf '  - %s\n' "${DEPENDENCIES[@]}"
        echo "[#] Applying dependencies first"
        FLAGGED=()
        for dep in "${DEPENDENCIES[@]}"; do
            FLAGGED+=("-d" "$dep")
        done
        "$0" "${FLAGGED[@]}"
        echo "[+] Dependencies applied"
        echo "[#] Applying main module '$1' now"
    fi
    
    TARGET="$("$DOTFILES_DIR/process" "$MODULE/.target")"
    TARGET="${TARGET/#\~/$HOME}" 
    echo "[+] Targeting '$TARGET'"
    
    if [[ ! -d "$TARGET" ]]; then
        echo "[!] Fatal: The target directory '$TARGET' does not exist or is not a directory"
        exit 6
    fi
    
    
    stow --target "$TARGET"                 \
         --dir "$DOTFILES_DIR"              \
         --ignore="^\.target$"              \
         --ignore="^\.stow-local-ignore$"   \
         --ignore="^\.dependencies$"        \
         --ignore="^\.is_not_dep$"          \
         --ignore="^\.dep_count$"           \
         --ignore="^\.gitignore$"           \
         --verbose                          \
         $1 2>&1
    
    if (( $? != 0 ));then
        echo "[!] Fatal: An error happened with stow"
        exit 7
    fi
    
    echo "[=] All '$1' symlinks successfully created"
    
    if (( $IS_DEP == 0 ));then
        touch "$MODULE/.is_not_dep"
    fi
    echo "$dep_count" > "$MODULE/.dep_count"  #if it hasn't been applied add count 
else 
    if (( $IS_DEP == 1 ));then #if it has already been applied, but it's a dependency, add count
        echo "$dep_count" > "$MODULE/.dep_count"
    fi
    echo "[=] Module has already been applied, skipping"
fi

shift 
if (( $# > 0 ));then
    echo "[#] Proceeding with next item"
    exec "$0" "$@"
fi
