set -g default-terminal "tmux-256color"
set -as terminal-features ",tmux-256color:RGB"

# VI mode
set-window-option -g mode-keys vi
bind-key Space copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Enable mouse usage
set -g mouse on

# Enable clipboard
set-option -g set-clipboard external
bind-key p run-shell "tmux set-buffer \"$(xclip -o -selection clipboard)\"; tmux paste-buffer"

# Start indexes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Hooks
set-hook -g alert-activity          'run-shell "~/.config/tmux/hooks/alert-activity'
set-hook -g alert-bell              'run-shell "~/.config/tmux/hooks/alert-bell" '
set-hook -g alert-silence           'run-shell "~/.config/tmux/hooks/alert-silence" '
set-hook -g client-active           'run-shell "~/.config/tmux/hooks/client-active" '
set-hook -g client-attached         'run-shell "~/.config/tmux/hooks/client-attached" '
set-hook -g client-detached         'run-shell "~/.config/tmux/hooks/client-detached" '
set-hook -g client-focus-in         'run-shell "~/.config/tmux/hooks/client-focus-in" '
set-hook -g client-focus-out        'run-shell "~/.config/tmux/hooks/client-focus-out" '
set-hook -g client-resized          'run-shell "~/.config/tmux/hooks/client-resized" '
set-hook -g client-session-changed  'run-shell "~/.config/tmux/hooks/client-session-changed" '
# set-hook -g command-error           'run-shell "~/.config/tmux/hooks/command-error" '
set-hook -g pane-died               'run-shell "~/.config/tmux/hooks/pane-died" '
set-hook -g pane-exited             'run-shell "~/.config/tmux/hooks/pane-exited" '
set-hook -g pane-focus-in           'run-shell "~/.config/tmux/hooks/pane-focus-in" '
set-hook -g pane-focus-out          'run-shell "~/.config/tmux/hooks/pane-focus-out" '
set-hook -g pane-set-clipboard      'run-shell "~/.config/tmux/hooks/pane-set-clipboard" '
set-hook -g session-created         'run-shell "~/.config/tmux/hooks/session-created" '
set-hook -g session-closed          'run-shell "~/.config/tmux/hooks/session-closed" '
set-hook -g session-renamed         'run-shell "~/.config/tmux/hooks/session-renamed" '
set-hook -g window-layout-changed   'run-shell "~/.config/tmux/hooks/window-layout-changed" '
set-hook -g window-linked           'run-shell "~/.config/tmux/hooks/window-linked" '
set-hook -g window-renamed          'run-shell "~/.config/tmux/hooks/window-renamed" '
set-hook -g window-resized          'run-shell "~/.config/tmux/hooks/window-resized" '
set-hook -g window-unlinked         'run-shell "~/.config/tmux/hooks/window-unlinked" '

# Fix broken numbers
set -g @tokyo-night-tmux_window_id_style 'none'
set -g @tokyo-night-tmux_pane_id_style 'hide'
set -g @tokyo-night-tmux_zoom_id_style 'none'
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin "tmux-plugins/tmux-yank"

# Run plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
run '~/.config/tmux/plugins/tpm/tpm'
